window._CCSettings = {
    platform: "web-mobile",
    groupList: ["default", "ball", "basket"],
    collisionMatrix: [
        [false, true],
        [true, false, true],
        [false, true, false]
    ],
    rawAssets: {
        assets: {
            f7EzAmuUNK96QVh0PhOAKu: ["resource/Audio/ClickEnd.mp3", 1],
            "97V1Mh98xCy6Dyb0nHpZnt": ["resource/Audio/ClickStart.mp3", 1],
            "c8XlDJoo5MibbjUsJpKow/": ["resource/Audio/heartbeat.mp3", 1],
            "5f+zUhd+hCqrbWd8mnAEhD": ["resource/Audio/mp3/Add_Force.mp3", 1],
            "09hgxowxtHMqVXI9S+25ld": ["resource/Audio/mp3/_HB_Basket_Bounce.mp3", 1],
            "20KtZbbmFDVJvov0s1Wqs7": ["resource/Audio/mp3/_HB_Basket_Bounce2.mp3", 1],
            "0fuhIY0+1CzKQzd/CLTAOn": ["resource/Audio/mp3/_HB_Basket_Rim.mp3", 1],
            "ccTcc0MgdHE750EmyG+Y/r": ["resource/Audio/mp3/_HB_Basket_ScoreNet.mp3", 1],
            "86SCWLh39JC7ZQfi2d/BNU": ["resource/Audio/mp3/ball_flame_on.mp3", 1],
            "63pttzPj9GX6hsma8+W6iS": ["resource/Audio/mp3/timeisout.mp3", 1],
            edgjC1l5JM5a1yGZ7htHYK: ["resource/Audio/voice/boom.mp3", 1],
            d4xy6H2M5Hz7O8FBMtqIuS: ["resource/Audio/voice/wauw.mp3", 1],
            "39sumKpnlOhIb2vO311pTu": ["resource/Audio/voice/yeah.mp3", 1],
            "574uhOk9dEcrhtCeIZGiZ2": ["resource/Bitmap Fonts/FredokaOne.png", 0],
            "d2M+C/O4dL0YFrOJex0glk": ["resource/Bitmap Fonts/HelveticaLight.png", 0],
            "9a+1afg11P8phOvjO+3aLP": ["resource/Bitmap Fonts/Slackery.png", 0],
            e7bRSp6FhOfLkgxlppSUfn: ["resource/Cocos Particles/backboard_broke.plist", 2],
            "54ydcBQ7BJ55jrfSx5rZCS": ["resource/Cocos Particles/backboard_shatter2.plist", 2],
            "28i/NeVEJDM53U3/X4SZE8": ["resource/Cocos Particles/ball_trail.plist", 2],
            d6yLYP99pFhbl6IRrhOuLr: ["resource/Cocos Particles/flame.plist", 2],
            "ad+o6ix6pASrbw+fNBLyLN": ["resource/Cocos Particles/goal_effect.plist", 2],
            d1hWmQyFxMMpxhFTuFXC4o: ["resource/Graphics/Game/backboard.png", 0],
            aeakpdEm5AQ4ofsOaBX76Z: ["resource/Graphics/Game/bottom-back.jpg", 0],
            "69MrdK/8lHiJXTP+ZB93lp": ["resource/Graphics/Game/broken_back_board.png", 0],
            e18NAu6eVPGbSE5XMPzYg8: ["resource/Graphics/Game/center-back.jpg", 0],
            "39zqUpr7JPt7wxfKUES4Y4": ["resource/Graphics/Game/fire_ball.png", 0],
            "c6H6Q0zLdHoZVDWzEpn/ol": ["resource/Graphics/Game/net1.png", 0],
            "92ER1QdGVLLaWRKdyIvAM/": ["resource/Graphics/Game/net2.png", 0],
            "66tQwdffhGp4HbjsXTE/gN": ["resource/Graphics/Game/normal_ball.png", 0],
            e4jc5KeE9B2JGZtxmRG2CI: ["resource/Graphics/Game/ring-back.png", 0],
            "9aL02yHFpL3rIgOcZdVvGN": ["resource/Graphics/Game/ring-front.png", 0],
            "61vG/WSJdC3JkmsYtm5TuL": ["resource/Graphics/Game/top-back.jpg", 0],
            "9b33yOEt5LUrFfZqtHm2bE": ["resource/Graphics/UI/button.png", 0],
            "2e8nCx+o5AE7pC91FZ1O1e": ["resource/Graphics/UI/home.png", 0],
            "98NELqqKVI0otoqweZlGMu": ["resource/Graphics/UI/line.png", 0],
            "18+FrLtaJKM7iglYhcDPr0": ["resource/Graphics/UI/more_game_pop_up_bg.png", 0],
            "15KXC3SHxN7L4JSjkvRcin": ["resource/Graphics/UI/oval.png", 0],
            "d4jeqSoMpKM6dgfOw/F+3t": ["resource/Graphics/UI/pause_icon.png", 0],
            "412fyuBPVHwLHWN/WIQmO+": ["resource/Graphics/UI/play_red.png", 0],
            "d1b4xm+uNMCKdTdEYU0sT6": ["resource/Graphics/UI/player_number.png", 0],
            "334c2m+KhNabOKjkE58GWh": ["resource/Graphics/UI/pop_up_closed.png", 0],
            "6cUgCvpEhAK7yxM8Qd/9Ct": ["resource/Graphics/UI/ring.png", 0],
            "832/qe/XdHpo/qJSw4Xh4e": ["resource/Graphics/UI/settings_icon.png", 0],
            "26wDJ4BRdB86G+8goCCeR3": ["resource/Graphics/UI/share_icon.png", 0],
            "1cTiZnBD9HGqzO/YgbtNHb": ["resource/Graphics/UI/soundfx_off_icon.png", 0],
            "95LKPHsyBDzKQkLjUOskK9": ["resource/Graphics/UI/soundfx_on_icon.png", 0],
            "964fOZ8DlOerpbXtZlrtNt": ["resource/Graphics/UI/start_top.png", 0],
            aff7aOd7FPApEpcMARmWKe: ["resource/Graphics/UI/tap_dunk1.png", 0],
            "4bap4Sm5NCrJhWZ4VJCYLP": ["resource/Graphics/UI/time_bar.png", 0],
            "20EK99pLtA97iY4YXEvG1Q": ["resource/Texture/FloatingAd_resources/erweima.b741d.png", 0],
            "53eMdsXA5N0riWfcgkcxvL": ["resource/Texture/FloatingAd_resources/whiteBk.png", 0],
            "64U9Yy81ZIyZMOagoKQjJ2": ["resource/Texture/black_transp.png", 0],
            "90OGCKoiBGtIMUwz7v3/ma": ["resource/Texture/singleColor.png", 0],
            "8beBlPSM1IBIFpNIO+kXTO": ["resource/leftView/cebian.png", 0],
            e7vFxJQqFK75UxlsUD36Ye: ["resource/leftView/cricleBtn.png", 0],
            "3dzjERzMZJka9a5sApHP9k": ["resource/leftView/texiaobg.png", 0],
            "81xkl0lYpNfpoAyt5+tyrG": ["resource/resources/Postacie/p1.png", 0],
            "22rH43CU5BzKKTlQR7QPEM": ["resource/resources/Postacie/p10.png", 0],
            a4T9N6uxtGk6OrtX0W5qJd: ["resource/resources/Postacie/p11.png", 0],
            "75atCc1PVPMqyYcX0SvADE": ["resource/resources/Postacie/p12.png", 0],
            "31zUV6uKlIvbKf3v6wWauV": ["resource/resources/Postacie/p13.png", 0],
            "f0YtWO0jtMAI/S3ZTqFSJV": ["resource/resources/Postacie/p14.png", 0],
            "6bZrPpC09K34zFS4OI+lOz": ["resource/resources/Postacie/p15.png", 0],
            "e4+WU9tPhLM5dCeyC54hKR": ["resource/resources/Postacie/p2.png", 0],
            "0as1TuTVVEF7aeVKw1lquc": ["resource/resources/Postacie/p3.png", 0],
            ffnwdyhctAy7FijenoZjxw: ["resource/resources/Postacie/p4.png", 0],
            "58KDyQY85H/LA4T4aq+YeT": ["resource/resources/Postacie/p5.png", 0],
            "b8UN/Zjn9F4JawyxzvmLYk": ["resource/resources/Postacie/p6.png", 0],
            "0eYVv5mEhLybAz1Aq20s78": ["resource/resources/Postacie/p7.png", 0],
            "9dnGE1UWNDt6VuOBT4Dtw7": ["resource/resources/Postacie/p8.png", 0],
            "60DmLDb5lNGbMkTpOI14aj": ["resource/resources/Postacie/p9.png", 0],
            "18IMUUVLdIh6hhAxMoU6Hj": ["resource/resources/audio/Basket_Ambience02_new.mp3", 1],
            "48J4VhQ5dH0ZFanC+On1M7": ["resource/resources/audio/Basket_applause02.mp3", 1],
            "6baSaQvfZFlq3DLxxq3IEl": ["resource/resources/audio/fireOthers.mp3", 1],
            f9KaVLShlNCZ8MKddKxxdr: ["resource/shareWx.png", 0],
            "23bwBV085Cb5fhRoO/USuz": ["resource/watchTv.png", 0]
        },
        internal: {
            "71VhFCTINJM6/Ky3oX9nBT": ["image/default_btn_disabled.png", 0],
            d8HsitJHxOYqo801xBk8ev: ["image/default_panel.png", 0],
            "6eBWFz0oVHPLIGQKf/9Thu": ["image/default_sprite.png", 0]
        }
    },
    assetTypes: ["cc.Texture2D", "cc.AudioClip", "cc.ParticleAsset"],
    launchScene: "db://assets/game.fire",
    scenes: [{
        url: "db://assets/game.fire",
        uuid: 4
    }, {
        url: "db://assets/main.fire",
        uuid: 0
    }],
    packedAssets: {
        "04752bd09": ["18AcrP2cpCTqbQ9O8DjDF7", 0, 1, 2, 3, "f9lNrEDiNL4agNYJDfPBab"],
        "0843b8cca": ["016GAi/MVHxIT8ErwKegYU", "032DcJnkJNwKLqMNwbgGkz", "05XD6sS/1G9bOwq4z8HwIA", "06k19qdgRMEYFqDVOlFzt6", "0btx609/FM9JvhaVPxmB5R", "13oO3ijtBBh7uaW7lCJUDl", "19o217hVxMwafMf3Y8lQcH", "1bbBr6+kJJH46sNF1HRN4g", "283BljnHZPC6Pa8DPlXDYK", "29FYIk+N1GYaeWH/q1NxQO", "2bLjV8+iJNebDtTLeS654A", "2egK6Wgj5JyI6hT5zl8Rgl", "2fxMJiUNxL3aSyNj8x67eQ", "30GLskTOZIG5+Jg942w870", "36n8WxYiFE1paKYIpt8PJz", "3aeMtuk+dIX7q+c/YJQpNc", "3a45/smrBNrJYuMl9A24Hk", "3b+g9Q8WpBV7tLboeZpI17", "3cNfti6d5Cxq2lO+Xx+S5C", "3drDlEJOVMnYdVFkIfVgY9", "41OExSDWtNhYJuygihM2+L", "41UZEdjk1Ib7rmAzP3sfRl", "42SCtztupDx6/dSogCW7S1", "42rpIr/qdBJpV38u1LKiFv", "42vFVzWrdOcbvxUM/h6FVd", "49+j7jAyVJI6XsgpfGDr2z", "4eY4V3+DxE2r1d79DCQwRQ", "51KtcTWZtLp6KeRUg9/NZ6", "51kVFLVZlCSpQ7SeQcefLS", "55ecWXQG1Ga7OufA5hL3Hf", "5d1/Z5UXJCWYaG0uY14E2a", "60IqepwjJO5pMYlMiFveYx", "63Z+Cw7phPJblslaz4VThL", "64g0YAuqRMELshGzJEdJn/", "67pxssFylPoLm3d7i6zfMZ", "68hs9Q6DlP5b4oGJGh2Jhu", "68oUT0uZFDUI4+a1/0ndQ5", "6aHXHbnPBL95j12Wlo+rKw", "6buW04UDtDBI+u1uhxSI1/", "6b48uYYedGbIEAqcT6R4KP", "76frhHTapATZACMJ7pJuY7", "785nMr4plI+pZ90dVJzQVD", "7bWQ1JP2dMhK58eKt3rpVB", "7fJwrBP39A87ap5vYgWS8A", "84u4yPj/pK6I/L76Z5n7tQ", "86W0AQcx9Mj5V98aX4Ugaw", "89EpGh6IBPPah4/9XqIFHi", "8cM3DvBCRFzrSfNYCEN9EL", "8c20Sso/ZEn7NUfNSM+EBh", "91sy60BIBFRpsBcWXK8EuS", "97d6oOyhRNPJ4diyRHBaRe", "989uO5xaFOhbsYCMYAF1Ue", "99+ybyCXpCJrBzJL3o+yDC", "9bvaMerUlDyary99mJa6xp", "a1DvaLKkxAxbBy1MtYmCGe", "a2qfwRzTFFloP+HaEGPBHS", "aa4n7+XIFK6r/fpnDx+MRT", 1, "b2kYu6lspLILft4lFtMXu4", "b4TpYiKhtNybFNyLhNvwyn", "b6RNcVVv1Bq4SrHc/myEo/", "b6d2T04ElDubK0Z89VAfiw", "baziMDJppIs6T4dv4eK5sB", "bfXEi0h11H6ZBc43NHeHjv", "c37H3bPNxC541qAgSTY/d0", "c4a2ozd8JDqKbsHm32S8k+", "c5wa5qfE9PPIV+rMKw/cqd", "cbo4y41vBHbIikBwFqtdsB", "ccY2hN5fRDnaruWRMB/D5V", "cfOU7IeJZG+IMoW5QTLsv/", "d2VLtJPghM9KacRm0xXXqC", 2, "d5633DzZ9HGKloCCpXbzZm", "daWqchn+JGtoaS4kl5ymoN", "db6qgAKiFOEouD0Hojd8RP", "dcH5uBl7tLXZLQ73YlLg0y", "dcow/w261D2L11j/7PEzzQ", 3, "e0pOOGbzRPw7E8oHzVw4HH", "eaH+gpJCFFC7p4WLiiI3BJ", "ebLlSScFJEdYig9x3b8mO0", "edFEHEBFpCQq/0Pmc2Ci98", "eeYc59eA1Gz4sQ4MGia3Su", "f3gL/1LYBNC5+3VCjo4yhs", 4, "f9iU75qJtK3KDShNgYESMF", "f98ksFNedL8Lskivj/jX5u", "fc32zPr49BubfcnbgN8evi", "feqU2/99VNbLdYw9Tq7xNa"],
        "0cecbedac": ["3bRu2ZCnZBdZs5MZyAq/qq", "5detV8rKdJYZEtfPejF7yR"]
    },
    orientation: "",
    uuids: ["7coZyLHFVMq7T0zUEKtkF7", "ac6wkhtolJc7Uh28gpblC3", "d5kJaJf2JE/LeqRyoGHEuU", "de/u6Lu7xEPoAi6MmvKCBM", "f45S0pEUVJJoulnXk9jDyz"]
};